sonar.projectKey=devops-formation-catalog
sonar.projectName=Catalogue Service
sonar.sources=src
sonar.tests=tests
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/integration/lcov.info
sonar.coverage.exclusions=tests/**,src/config/swagger.js
