#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


npx commitlint --from origin/main --to HEAD --verbose || {
  echo ""
  echo " Tip: Instead of writing commits manually, use:"
  echo "   npx cz"
  echo "   It will guide you through the correct format."
  echo ""
  exit 1
}